Repository abdallah-zaghloul/nuxt-google-sheet, pull requests merged in 2024-05, with the labels that each got.

#6 Feature/sheets page
  assets/css/global.css
  assets/images/empty-state.webp
  components/Card.vue
  components/ConnectedUser.vue
  components/SetupGuide.vue
  components/Sheets.vue
  components/Sheets/Sheets.vue
  components/Sheets/SheetsTable.vue
  components/Sheets/helpers.ts
  pages/index.vue
  uno.config.ts
Labels: Reviewed

#7 Feature/bulk sync page
  assets/css/global.css
  components/BackNavButton.vue
  pages/bulk-sync.vue
  pages/index.vue
  tsconfig.json
Labels: Reviewed

#11 Refactor
  server/composables/googleService.ts
  server/composables/settingRepository.ts
  server/composables/settingService.ts
  server/composables/sheetRepository.ts
  server/composables/sheetService.ts
  server/routes/google/auth-callback.get.ts
  server/routes/setting/index.get.ts
  server/routes/setting/index.post.ts
  server/routes/sheet/index.post.ts
  server/utils/schemas.ts
  server/utils/types.ts
  types.ts
Labels: Reviewed

#12 Refactor
  composables/useApi.ts
  server/utils/handler.ts
  server/utils/schemas.ts
Labels: Reviewed

#13 Feature/fetch sheets
  server/composables/sheetRepository.ts
  server/composables/sheetService.ts
  server/routes/sheet/index.get.ts
  server/utils/schemas.ts
  server/utils/types.ts
  server/utils/validator.ts
Labels: Reviewed

#14 show sheet by valid id or not found
  server/composables/sheetRepository.ts
  server/composables/sheetService.ts
  server/routes/sheet/[id].get.ts
  server/utils/handler.ts
  server/utils/schemas.ts
  server/utils/validator.ts
Labels: Reviewed

#15 Feature/single sheet page
  components/BackNavButton.vue
  components/SheetConfiguration.vue
  components/Sheets/Sheets.vue
  package.json
  pages/index.vue
  pages/sheet/[id].vue
Labels: Reviewed

#16 Feature/delete sheet
  server/composables/sheetRepository.ts
  server/composables/sheetService.ts
  server/routes/sheet/[id].delete.ts
Labels: Reviewed

#18 update sheet
  server/composables/googleService.ts
  server/composables/sheetRepository.ts
  server/composables/sheetService.ts
  server/routes/sheet/[id].patch.ts
  server/utils/schemas.ts
  server/utils/types.ts
Labels: Ready for review

#20 add disconnect and connect functionality
  components/ConnectedUser.vue
  components/Setting.vue
Labels: Reviewed

#21 Refactor
  server/composables/sheetRepository.ts
  server/utils/handler.ts
Labels: Reviewed

#22 fix: don't create sheet unless setting is connected
  server/routes/sheet/index.post.ts
Labels: Reviewed

#23 MVP documentation
  .env.example
  README.md
Labels: documentation, Reviewed

#25 sync created order at syncable sheets
  .env.example
  server/composables/googleService.ts
  server/composables/sheetRepository.ts
  server/composables/sheetService.ts
  server/composables/youcanService.ts
  server/routes/callback/youcan/sync-order.post.ts
  server/routes/sheet/[id].patch.ts
  server/routes/sheet/sync.post.ts
  server/utils/check.ts
  server/utils/getCurrentSession.ts
  server/utils/getNestedProp.ts
  server/utils/schemas.ts
  server/utils/types.ts
Labels: Reviewed

#28 unAuthorize error in case of no google client credentials
  nuxt.config.ts
  server/composables/googleService.ts
  server/composables/mediatorService.ts
  server/composables/settingService.ts
  server/routes/callback/google/auth.get.ts
  server/routes/callback/youcan/sync-order.post.ts
  server/routes/setting/index.get.ts
  server/routes/setting/index.post.ts
  server/routes/sheet/[id].delete.ts
  server/routes/sheet/[id].get.ts
  server/routes/sheet/[id].patch.ts
  server/routes/sheet/headers.get.ts
  server/routes/sheet/index.get.ts
  server/routes/sheet/index.post.ts
  server/routes/sheet/sync.post.ts
  server/utils/handler.ts
  server/utils/helper.ts
  server/utils/validator.ts
Labels: Reviewed

#29 auto/manual sync orders
  .gitignore
  server/composables/googleService.ts
  server/composables/youcanService.ts
  server/routes/callback/youcan/sync-order.post.ts
  server/routes/sheet/auto-sync.post.ts
  server/routes/sheet/index.get.ts
  server/routes/sheet/manual-sync.post.ts
  server/routes/sheet/sync.post.ts
  server/utils/helper.ts
  server/utils/schemas.ts
  server/utils/types.ts
Labels: Reviewed
